### ISSUE TITLE
Where is the file, edit, helptoolbar as stated in the document

### ISSUE THREAD

**Issue by stevensrf11** [DinoChiesa/XPathVisualizer#1]
The help.rtf file talks about File, Edit, Help menu's in the application available for download.
Exactly where is the menu in the applicaiton.
I do not see it when I run the application.
The Menus 
The application is a traditional Windows app. You’ll find the menu strip at the top, very familiar and similar to other applications. 
The File Menu
File…New creates a new, blank XML document.  You can paste XML into the box to fill it in, or just type. You can also create a new document at any time with the ctrl-N shortcut. 
File…Open opens an XML document from the file system.  The shortcut for File…Open is ctrl-O. 
You can also use File…Get to retrieve one from an HTTP

**Comment by cschweers** [comment]
The menu bar is deactivated by default. To activate it and make it visible, simply press the 'Alt' key.

**Comment by DinoChiesa** [comment]
I think if you press/hold the ALT button, or hover your mouse at the top of the window where the menu strip "ought" to be, the menu strip should appear.
I don't believe there is a way to make the menu strip stay visible, without rebuilding the tool.

**Comment by stevensrf11** [comment]
I commented out the code that hides the menu bar at start up.

Yes I found alt + O keys made the menu bar appeared.

 

 
 

Sent: Monday, May 09, 2022 at 3:05 PM

**Comment by DinoChiesa** [comment]
Excellent.  Glad you got it sorted.
